name: Test & Build Gamedoora-UI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.x
      env:
        NODE_ENV: development
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
      
    - name: Add execute permissions to script
      run: chmod +x ./deploy.sh

    - name: Build and deploy
      id: deploy
      run: ./deploy.sh
      env:
        SSH_PASS: ${{ secrets.SSH_PASSWORD }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_HOST: ${{ secrets.SSH_HOST }}